### ISSUE TITLE
Citation Request in Your Paper

### ISSUE THREAD

**Issue by tshu-w** [wbsg-uni-mannheim/TailorMatch#1]
Dear Authors, I am the author of the paper entitled "[Match, Compare, or Select? An Investigation of Large Language Models for Entity Matching](https://arxiv.org/abs/2405.16884)" (https://github.com/tshu-w/LLM4EM). 

Our paper investigated three different prompt strategies for LLM-based EM and proposed a compound EM framework. Our approaches are complementary, and I believe that referencing our work in related work makes it more valuable to the audience who are interested in LLM-based entity matching.

**Comment by Aaron9812** [comment]
Hi there,
We plan to cite your paper in the next revision of our own paper.

Additionally, I wanted to ask if you have already experimented with fine-tuning using your Compare and Select approaches. I believe your methods could potentially perform better than standard fine-tuning.

**Comment by tshu-w** [comment]
> We plan to cite your paper in the next revision of our own paper.

It would be much appreciated.

> Additionally, I wanted to ask if you have already experimented with fine-tuning using your Compare and Select approaches. I believe your methods could potentially perform better than standard fine-tuning.

Not yet in this paper. As discussed in limitation section, it could be further work.
